### PR TITLE
Add GapDeque

### PR DESCRIPTION
**Pull request by Spartan322**
See #170
Add utility::any_of concept

### CODE REVIEW

**Comment by wvpm** [comment]
Would it be possible/feasible to write unit tests for the GapDeque?
I think the code looks alright but I can't predict how well it will work.

**Comment by Spartan322** [comment]
Does kinda mean we'll have to integrate a unit test system, I don't think that's the responsibility of this PR at least.

**Comment by Spartan322** [comment]
Currently preferring to investigate the viability of https://github.com/mattreecebentley/plf_hive instead.

**Comment by Spartan322** [comment]
Should be resolved by #170.

**Pull request closed without merging**
